CREATE TABLE photos (
  id int(11) NOT NULL AUTO_INCREMENT,
  event_name varchar(255) DEFAULT NULL,
  event_id int(11) DEFAULT NULL,
  title varchar(255) DEFAULT '',
  event_date date DEFAULT NULL,
  description text DEFAULT NULL,
  image_url varchar(500) NOT NULL,
  thumbnail_url varchar(500) DEFAULT NULL,
  faculty varchar(100) DEFAULT NULL,
  academic_year varchar(20) DEFAULT NULL,
  file_hash varchar(32) DEFAULT NULL,
  user_id int(11) NOT NULL,
  created_by int(11) DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  deleted_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_photos_event_hash (title,file_hash),
  KEY user_id (user_id),
  KEY idx_photos_faculty (faculty),
  KEY idx_photos_academic_year (academic_year),
  KEY fk_photos_event_new (event_id),
  CONSTRAINT photos_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;