CREATE TABLE IF NOT EXISTS history_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  action VARCHAR(100) NOT NULL,
  target_type VARCHAR(50),
  target_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);